#!/usr/bin/env ruby

Dir["./app/**/*.rb"].each { |f| require f }
Dir["./lib/**/*.rb"].each { |f| require f }

Environment.environment = ENV["DB"] || "development"

def clean_gets
  (gets || "").chomp
end

zombie = %q{
NUGGGGGH MUST EAT BRAINS
                           \
                                .....
                               C C  /
                              /<   /
               ___ __________/_#__/
              /(- /(\_\________   \
              \ ) \ )_      \o     \
              /|\ /|\       |'     |
                            |     _|
                            /o   __\
                           / '     |
                          / /      |
                         /_/\______|
                        (   _(    <
                         \    \    \
                          \    \    |
                           \____\____\
                           ____\_\__\_\
                         /`   /`     o\
                         |___ |_______|.. .
}

def add_skill_to_training_path(training_path)
  puts "What skill do you want to add?"
  name = clean_gets
  skill = Skill.create(name: name, training_path: training_path)
  if skill.new_record?
    puts skill.errors
  else
    puts "#{name} has been added to the #{training_path.name} training path"
  end
end

puts zombie

training_paths_controller = TrainingPathsController.new()

training_paths_controller.list

command = clean_gets

case command
when "add"
  training_paths_controller.add
when /\d+/
  training_paths_controller.view(command.to_i)
else
  puts "I don't know the '#{command}' command."
end
