#!/usr/bin/env ruby

Dir["./app/**/*.rb"].each { |f| require f }
Dir["./lib/**/*.rb"].each { |f| require f }

zombie = %q{
NUGGGGGH MUST EAT BRAINS
                           \
                                .....
                               C C  /
                              /<   /
               ___ __________/_#__/
              /(- /(\_\________   \
              \ ) \ )_      \o     \
              /|\ /|\       |'     |
                            |     _|
                            /o   __\
                           / '     |
                          / /      |
                         /_/\______|
                        (   _(    <
                         \    \    \
                          \    \    |
                           \____\____\
                           ____\_\__\_\
                         /`   /`     o\
                         |___ |_______|.. .
}

puts zombie
command = gets
puts "What training path do you want to add?"
name = (gets || "").chomp
training_path = TrainingPath.create(name: name)
if training_path.new_record?
  puts training_path.errors
else
  puts "#{name} has been added to the list of training paths"
end
